# Generated by Django 6.0.1 on 2026-01-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='pphone',
        ),
    ]
