# Generated by Django 6.0.1 on 2026-01-13 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_phone_user_pphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pphone',
            new_name='phone',
        ),
    ]
