# Generated by Django 6.0.1 on 2026-01-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_pphone_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='service_type',
            field=models.CharField(choices=[('emergency', 'Emergency SOS'), ('fuel', 'Fuel Delivery'), ('jump_start', 'Jump Start'), ('towing', 'Towing'), ('lockout', 'Lockout'), ('repair', 'Mechanical Repair'), ('general', 'General Service'), ('cleaning', 'Car Wash')], max_length=20),
        ),
    ]
