# Generated by Django 6.0.1 on 2026-01-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='request',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='technician',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
