# Generated by Django 6.0.1 on 2026-01-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_feedback_customer_remove_feedback_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
