# Generated by Django 6.0.1 on 2026-01-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_servicerequest_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='is_cost_approved',
            field=models.BooleanField(default=False),
        ),
    ]
